title: Tyler Kuromiya Parker
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.tkkp.dev" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Tyler Kuromiya Parker # add your name
author-img: tyler_parker.jpg # add your photo
about-author: I am a python developer with a background in mechanical engineering. I enjoy books, beer, and bicycles. # add description
social-twitter: tylerkp # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: tylerkkp # add your Github handle
social-linkedin: tyler-parker # add your Linkedin handle
social-email: tylerkkp@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: UA-178123215-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
