title: Tyler Kuromiya Parker
description: > # this means to ignore newlines until "baseurl:"
  Personal website and blog for Tyler Kuromiya Parker. I write about: technology, data, books, 
  beer, programming, bicycling, hiking, finance, and other topics of personal interest. I live 
  in the beautiful Pacific Northwest, sandwiched between Seattle, WA and Vancouver, BC. 
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.tkkp.dev" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Tyler Kuromiya Parker # add your name
author-img: tyler_parker.jpg # add your photo
about-author: I am a python developer with a background in mechanical engineering. I enjoy books, beer, and bicycles. # add description
social-twitter: tylerkp # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: tylerkkp # add your Github handle
social-linkedin: tyler-parker # add your Linkedin handle
social-email: tylerkkp@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
